### ISSUE TITLE
Chat Notifications / group management UI problems 

### ISSUE THREAD

**Issue by Rokeugon** [A3Wasteland/ArmA3_Wasteland.Altis#265]
ive recently stumbled upon a very annoying problem recently.. im getting no chat pop-ups on any A3wasteland server 

and my player menu - when i go to group management it just says [PLAYER] and i cannot invite anyone etc

tried switching independent and to bluefor and nothing works.. the chat problem is even worse because when i type and send it. it does not appear on my screen where chat messages are supposed to go... same goes with i get no server notifications in chat (Etc)

is this happening to just me or are other people getting this problem as well. i used to be able to chat and invite without problems but it just started all of a sudden about 2 days ago...

ive also posted this on the A3wasteland forums as im confused as to who this is effecting : http://forums.a3wasteland.com/index.php?topic=1027.0

**Comment by AgentRev** [comment]
http://forums.a3wasteland.com/index.php?topic=888.0

**Comment by JoSchaap** [comment]
Is your game by any chance set to the streamfriendly setting?


Verzonden vanaf Samsung Mobile

-------- Oorspronkelijk bericht --------
Van: Rokeugon <notifications@github.com> 
Datum:17-01-2015  13:15  (GMT+01:00) 
Aan: "A3Wasteland/ArmA3_Wasteland.Altis" <ArmA3_Wasteland.Altis@noreply.github.com> 
Onderwerp: [ArmA3_Wasteland.Altis] Chat Notifications / group management UI
  problems  (#265) 

ive recently stumbled upon a very annoying problem recently.. im getting no chat pop-ups on any A3wasteland server

and my player menu - when i go to group management it just says [PLAYER] and i cannot invite anyone etc

tried switching independent and to bluefor and nothing works.. the chat problem is even worse because when i type and send it. it does not appear on my screen where chat messages are supposed to go...

is this happening to just me or are other people getting this problem as well. i used to be able to chat and invite without problems but it just started all of a sudden about 2 days ago...

ive also posted this on the A3wasteland forums as im confused as to who this is effecting : http://forums.a3wasteland.com/index.php?topic=1027.0

**Comment by AgentRev** [comment]
already told him

**Comment by JoSchaap** [comment]
Rgr :) phone hung when i clicked the forum link, so i just went in blind :)


Verzonden vanaf Samsung Mobile

-------- Oorspronkelijk bericht --------
Van: Agent Revolution <notifications@github.com> 
Datum:17-01-2015  14:08  (GMT+01:00) 
Aan: "A3Wasteland/ArmA3_Wasteland.Altis" <ArmA3_Wasteland.Altis@noreply.github.com> 
Cc: "Johan Schaap (.nl)" <johan@johanschaap.nl> 
Onderwerp: Re: [ArmA3_Wasteland.Altis] Chat Notifications / group management
  UI problems  (#265) 

already told him
