### ISSUE TITLE
Player saving not timed well

### ISSUE THREAD

**Issue by micovery** [A3Wasteland/ArmA3_Wasteland.Altis#266]
https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/blob/af64eaf9c8a3cd2586b7e8d4ab440918245f97d7/client/init.sqf#L70-L88

Since each player sends a save request every 60 seconds ... Imagine, a server with 60 or more players connected.  They don't all necessarily send their request at the same time.

 On a full server, this effectively causes the server to be busy saving data all the time.

Some solutions could be:

1. Have a server-side loop that triggers a mass player save every X seconds.
2. Change the client side loop to only execute every multiple of X  using```ceil(serverTime)```
3. A server-side loop similar to the one from point 1, but .. instead it just hints to all players using ```publicVariable``` that they should go ahead and save their data.

**Comment by AgentRev** [comment]
I don't see why would that be a problem. I find it much better to have any kind of processing spread over a long period rather than causing a lag spike by doing everything in an instant. This is also the main reason why vehicles and objects are saved at alternate intervals, and also why I wrote fn_loopSpread for the entity caching scripts and evaluation of managed player actions.

**Comment by micovery** [comment]
Supposed, you are right ...  you still have no guarantee that they are all going to be spread uniformly. Closing, as per your comment, 'as-designed'.

**Comment by AgentRev** [comment]
Yeah no guarantee, but random order is enough for me. It's not like it's causing any kind of problem anyway.
