### ISSUE TITLE
Player reset

### ISSUE THREAD

**Issue by LouDnl** [A3Wasteland/ArmA3_Wasteland.Altis#271]
I've been having some players complain about a character reset. They log in invisible, respawn, spawn invisible again or spawn in with full military gear. Seems to me like a connection to database issue.

Steps one player did:
They log in invisible (I can't get this reproduced myself), try to respawn but are still invisible. Shut down arma and start back up. Log back in and spawn in in full military gear. This guy whent to the bank to withdraw money and got an 'not enough balance' error and his bank money whent from 145k to 0.

Don't have any logs because of the 1.38 bug that makes me use -noLogs :(

**Comment by JoSchaap** [comment]
turn on logs and see if it happens again, without logs there really isn't any way we can look into this :)

**Comment by LouDnl** [comment]
I don't think you want to look through 1GB + of text in one log. I'll wait for the 1.38 log spam fix first.

**Comment by JoSchaap** [comment]
search +  replace on the physx crap :P

**Comment by Classifed787** [comment]
So far I have only had this happen once on my server and thankfully it was to one of my admins on my test server. But we have not had it happen since. We thought at the time it was just his connection so he disconnected and backed all the way out and came back in and he was visible then, but he never mentioned anything about his bank account going to zero. I will try and go through my logs cause it was on my test server so the logs are a lot smaller, no where near 1GB.

**Comment by LouDnl** [comment]
This is related to: https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/issues/244
