### ISSUE TITLE
Can't pick up spawn beacons

### ISSUE THREAD

**Issue by hobart666** [A3Wasteland/ArmA3_Wasteland.Altis#344]
I'm having an issue where we cant pick up a packed up spawn beacon weather it was stolen or dropped from inventory. I'm using a hybrid mission of LouD's (older) altis mission and A3wasteland 1.2 vanilla

**Comment by LouDnl** [comment]
We've been having this since when the spawn beacon turned into a rolled up sleeping bag when dropped. But we've been having it with other items too. It has to do with the lineIntersects command in takeable.sqf. I disabled the whole check in my mission and changed the take distance to 1 mtr. This helps ;)

**Comment by hobart666** [comment]
thank you sir! will get that worked out.

**Comment by LouDnl** [comment]
It's not a fix but a workaround:
https://github.com/LouDnl/ArmA3_Wasteland.Altis/commit/9aafbfeb28ce11ac72c61ed23aa9679003520642

**Comment by hobart666** [comment]
Rgr tht, It is definitely working for now.
