### ISSUE TITLE
another bis_fnc_execvm issue ?

### ISSUE THREAD

**Issue by ghost** [A3Wasteland/ArmA3_Wasteland.Altis#374]
Hi, 

There is another '11:06:37 Scripting function 'bis_fnc_execvm' is not allowed to be remotely executed' issue i believe found here 

C:\Users\Matt\Desktop\ArmA3_Wasteland.Altis-dev\server\functions\network\fn_MPexec.sqf:
  110       _isWhitelisted = [["A3W_fnc_", "mf_remote_"], _functionName] call fn_startsWith;
  111  
  112:      _defineServerRules = (_functionName == "BIS_fnc_execVM" && {_params param [1, "", [""]] == "client\functions\defineServerRules.sqf"});

**Comment by AgentRev** [comment]
This does not call the function, it's a mere text filter...

**Comment by ghost** [comment]
ah ok my bad, i must have left another somewhere then.

**Comment by AgentRev** [comment]
I believe that `BIS_fnc_execVM` is still called via `BIS_fnc_MP` by the game core, in initFunctions.sqf from functions_f.pbo during client compile. It's basically what triggers initPlayerServer.sqf in mission PBOs. But you definitely do not want to whitelist `BIS_fnc_execVM`, otherwise kids can easily run server-side code.

I guess the only solution is to let it be, and shame BIS.
