### ISSUE TITLE
KIA Mission End Screen

### ISSUE THREAD

**Issue by JA3S** [A3Wasteland/ArmA3_Wasteland.Altis#417]
Hello A3Wasteland Team,

When player dead, A3Wasteland respawn dialog comes up but also the KIA Mission End (Standard Arma 3 Screen). I can click on respawn and player respawns but the KIA screen stays. Only thing you can do is click on END button, this kicks you back to lobby. Then rejoin the game.

I tested your A3Wasteland 1.2b plain vanilla mission .....no problem.
(I created my mission file in 3D Editor that seems to be the problem.)
I just put my mission file into plain vanilla A3W 1.2b and have the KIA End Mission issue.

I will redo my mission file in 2D mode.

Just thought you may want to know.
Have a great day

**Comment by AgentRev** [comment]
check your `respawn` option in description.ext, it should be `"BASE";`

Also the 2D editor is going to be permanently removed in 3 days, so you should avoid using it.

**Comment by annihilator825** [comment]
Hi AgentRev,

I am now having the same problem. I checked my description.ext and it is set to `"BASE";`
Do you have any other ideas?

Thank you!
Alex

**Comment by AgentRev** [comment]
No, I don't even know how you guys manage to mangle the mission to that point the first place, I've never seen or heard about it outside of this GitHub issue in 4 years.

**Comment by Soloknight** [comment]
Check your mission.sqm in Preferences to respawning to off

**Comment by hobart666** [comment]
I think they are replacing the original mission.sqm but ya mangle, lol I
thought I was the mangler, I guess not as much as I thought.

On Mar 30, 2017 6:13 AM, "Agent Revolution" <notifications@github.com>
wrote:

No, I don't even know how you guys manage to mangle the mission to that
point the first place, I've never seen or heard about it outside of this
GitHub issue in 4 years.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/issues/417#issuecomment-290365619>,
or mute the thread

**Comment by annihilator825** [comment]
I am indeed mangling it pretty bad because I'm doing a total conversion to CUP maps/units/items. I found the solution though (dumb mistake) - apparently in the Eden editor there is now a checkbox to select "Singleplayer Death Screen" and I somehow managed to tick that.

Thanks guys.

**Comment by AgentRev** [comment]
Glad to hear.
