### ISSUE TITLE
Teamkiller disconnected punish not working

### ISSUE THREAD

**Issue by codexGW** [A3Wasteland/ArmA3_Wasteland.Altis#427]
If someone kills a teammate and leaves before the teammate can respawn, the punish screen doesn't come up. Word has spread about this and players are abusing it.

**Comment by AgentRev** [comment]
wrote a fix, will test friday

**Comment by AgentRev** [comment]
https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/commit/04c4db15e6cf09fecc41231c448d55ea48ffaf22

**Comment by HAVOCWIZARD** [comment]
Thx, rev, will this also work for ind. because they are abusing that as well to get money, killing each other, i found tonight after loading the latest update you made a few hours ago, i do get the negative scores, and i was trying now to use that on the ind. to drop only $10 after the score is -2, had players with -13 and more tonight...but i am doing something wrong code wise, "still noobs". i trying to check the deathscore on onkilled.sqf where player drops all, but i think im not getting the value correct.

**Comment by codexGW** [comment]
Not sure if this will fix vanilla but we were getting -scores on our scoreboard but they have been fixed by the guy who modded the scoreboard. Haven't tried the newest team kill commit though.
https://github.com/A3Armory/A3A_A3Wasteland.Altis/commit/7fec1b7258d98e84a219db33f209820fd92a3884
https://github.com/A3Armory/A3A_A3Wasteland.Altis/commit/6b6103eacd213e145a5867066c9be3886ea3afcd

**Comment by AgentRev** [comment]
Indie is the team where people end up when they are punished. Punishes are only available to Blufor and Opfor. None of this has to do with the 2 above comments.

You can get the number of teamkills with `_teamkills = [_player, "teamKills", false] call fn_getScore;`. You should **not** change the drop money under any circumstance, but rather the **starting money** instead.

**Comment by HAVOCWIZARD** [comment]
Thx rev. Sorry im being a noob here. Indies= independent right or is there another function that i dont use in the vanilla?

**Comment by AgentRev** [comment]
yes
