### ISSUE TITLE
ATM Removed my money

### ISSUE THREAD

**Issue by TK-Tyrant** [A3Wasteland/ArmA3_Wasteland.Altis#432]
As the title shows, I lost all of my money in my ATM some how, I recently got 300k (The Max) and was playing normally until I just checked my money and it was 0. I checked if it was a visual glitch by trying to withdraw $50 in an attempt to fix something. I relaunched my game from scratch from steam and still gone.

I'm not sure how much a picture of it will help my case about actually having that much since you could always argue that I did have that much and just pooled money together, you get the idea.

http://images.akamai.steamusercontent.com/ugc/491276577389556949/133D87E759C5F094791527CC28B02B1B8B86258F/

I do not know how to recreate this. American Pride has told me that this DOES happen sometimes, not likely, but does happen. This issue is incredibly annoying as I recently got the money just to have all of it taken away.

**Comment by ghost** [comment]
are you a player or server owner?

**Comment by nerdalertdk** [comment]
I'm guessing player

> Joined on 16 Aug 2016

**Comment by ghost** [comment]
Maybe joined the wrong server?, never had a report of lost bank money before

**Comment by TK-Tyrant** [comment]
Player.

It was very much the right server as I had it all in one life, died, then it was all gone.

**Comment by ghost** [comment]
Have you approached the owners/community that runs it?

**Comment by JoSchaap** [comment]
Please contact the server host. 
GiT is for reporting issues with the mission code purely.

**Comment by AgentRev** [comment]
I investigated this very issue a year ago (https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/issues/244) but I was not able to find a root cause. The closest I got to an answer is that there could be a rare engine bug where respawning is not taking place correctly, resetting variables to 0.

A possible fix that would be to track bmoney changes via addPublicVariableEventHandler's alt syntax from A3 v1.46 and restore that on respawn, but according to Killzone Kid it might not work as expected.

**Comment by codexGW** [comment]
This was a player from our servers. I told him to report it here or the a3w forums if he wanted a refund. This has been reported only 3 times and this is the only time someone has reported it since we switched to extDB. I'm sure its happened a lot more then 3 times but still very rare. I have heard admins talk about it before and most players are to lazy to report it.

**Comment by ghost** [comment]
Wow I've had a report to, the first one

Well i played with my friend yesterday, and we got killed then after we respawned he could't see me or that i even was on the server so i decided to relog and after i relogged i saw that my bank was at 0 when it originally was at around 1.2 million which caused me to feel a little annoyed and decided to just quit to see if it came back at next restart or something like that but that didn't happen so i wonder if its possible to roll it back or something or if i have to earn it back which i don't really feel like to doing now. My in-game name is Painze / [PbN] Painze.

**Comment by AgentRev** [comment]
To properly investigate such anomalies, I require:
- UID of the affected player
- Server RPT at the time of disconnect
- Server RPT at the time of reconnect
- extDB debug log at the time of disconnect
- extDB debug log at the time of reconnect

which requires the extDB debug DLL instead of the regular one.
