### ISSUE TITLE
Thoughts on Dynamic Simulation

### ISSUE THREAD

**Issue by codexGW** [A3Wasteland/ArmA3_Wasteland.Altis#459]
[Dynamic simulation](https://community.bistudio.com/wiki/Arma_3_Dynamic_Simulation) is coming out next update. I think it would work best on empty vehicle spawns, loot spawns, and missions that don't have moving vehicles. It might not be bad idea to add it to certain player dropped items too. Then add default config settings for setDynamicSimulationDistance = "Group", "Vehicle", "EmptyVehicle" and "Prop". Any thoughts on this and do you think it would be worth the effort?

**Comment by hobart666** [comment]
Oh this is neat, kinda like some of the AI scripts for exile that freeze so
until a player is within a certain distance. This is kinda Sweet. I wonder
if they'll finally bring the dogs out of beta now. ...We need dogs, that
attack.

**Comment by AgentRev** [comment]
I will look into it, it's nearly identical to my vehicle manager so don't expect any significant gains, but an official solution is always nice to have.

Note that I do not freeze AI because if they shoot while frozen, then you hear the sound as it they were right behind you, even if they are very far away. It's one of the bugs with simulation disabling. Have you ever heard random machine gun reloading sounds very close to you? Those are from armed offroads in the distance. When I was a Breaking Point dev, I actually tried disabling simulation on distant players, many spooks were had, because you'd hear gun sounds at full volume every time someone outside render distance would shoot.

https://feedback.bistudio.com/T75757

**Comment by codexGW** [comment]
That's a bummer about the AI. I think that could have helped. It could help with the [loot spawn](https://github.com/A3Armory/A3A_A3Wasteland.Altis/tree/dev/addons/simple_lootspawner) we use and the other city loot spawns and mission spawned items maybe. This might make that laggy cancer causing loot spawn that comes with A3W usable. Maybe adding it to player dropped items too, so they don't have to delete them so often.

**Comment by codexGW** [comment]
Oh yeah, do you think this will be worth adding to R3F items?

**Comment by AgentRev** [comment]
I said it many times, GroundWeaponHolder is not simulated; including it in a simulation manager has pretty much no effect whatsoever.

If BIS would fix the sound bug, I could probably give the client a 50% FPS boost. But they don't give a shit. I think that issue got like over 100 upvotes on the old tracker, Deathlyrage had tweeted it out.

What do you mean about R3F?

**Comment by codexGW** [comment]
Yeah I though as much about the GroundWeaponHolder. Thanks for the info. I never noticed a difference with our loot spawn off or on. I think Matt's cleanup issue might have gotten to my head.

**Comment by codexGW** [comment]
Do you think R3F town spawned items and bases can benefit from this?

**Comment by AgentRev** [comment]
If it falls down, it's simulated. If it stays up in the air, it's not.

**Comment by codexGW** [comment]
Ah I see, that makes sense. Thanks again!

**Comment by ghost** [comment]
Not sure how you dragged me into this :-0 two different subjects :-)
