### ISSUE TITLE
AI kills not counting with UAV's

### ISSUE THREAD

**Issue by hobart666** [A3Wasteland/ArmA3_Wasteland.Altis#472]
SO I was informed by someone paying attention that AI kills aren't registering to scoreboard, player kills are registering without a problem and it's while using any uav. Anyone have any thoughts on this?

**Comment by AgentRev** [comment]
AIs are not hooked up to A3W's kill tracking system, because it's very closely tied to revive; obviously we don't want AIs with revive.

I wrote many improvements to kill tracking within the last couple months to pave the way for a proper kill log, but was stopped short due to schoolwork. UAV kills in particular should register way better. However I probably won't be able to push the code until this summer, because it's not complete and needs a lot more testing.

**Comment by hobart666** [comment]
No worries Rev, I figured I'd mention it here before I started breaking the
mission.

Oh yea I saw something about bounties in your git is that coming this
summer as well?

**Comment by AgentRev** [comment]
Maybe. The bounty system was made by A3Armory and is fully working, I think the only change needed to make it compatible is to adapt the scoreboard to show the bounty amount.

**Comment by hobart666** [comment]
Oh sweet!

**Comment by AgentRev** [comment]
https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/commit/983de3ea96de8c95cdafcb8106f4564a46f488a6
