### ISSUE TITLE
Lynx Rifle and Storage

### ISSUE THREAD

**Issue by ghost** [A3Wasteland/ArmA3_Wasteland.Altis#504]
Hi

For some odd reason i cannot figure out you cannot add the Lynx rifle to personal storage. 

i have test this on mine and vanilla wasteland to make sure. 

any ideas Rev?

**Comment by AgentRev** [comment]
The storage container is limited by Bohemia. Unless they add some sort of `setMaxLoad` command to increase inventory storage space, there is no hope.

I don't even think they would consider adding that command, because for it to work smoothly they'd have to change a bunch of stuff everywhere so that dynamic max load would be taken into account instead of the hardcoded config value. TBH I find it retarded that they didn't do it dynamic from the get-go.
