### ISSUE TITLE
Game will freeze for a short time (around half second) when trying to acquire a target lock in a jet

### ISSUE THREAD

**Issue by Jermin** [A3Wasteland/ArmA3_Wasteland.Altis#508]
If you press the T or R key (which is for locking targets in jets) consecutively, you can clearly see the game is stuttering. Singleplayer and other Multiplayer game modes don't have this issue.

This issue exists on the vanilla mission, too.

**Comment by AgentRev** [comment]
I don't know, I wouldn't even know where to begin looking into, because there are no scripts that trigger on target locking. Personally, I don't recall experiencing stutter. I remapped `Lase range, Lock range, Reveal target` to `Mouse Btn. #4` and `Next target (in vehicle) `to `Tab`. Literally the only thing related to targeting is this, which runs every second, not linked to T or R keys: https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/blob/d8c81f13b42fcb1c2cdabcdf195780727203e174/client/systems/hud/playerHud.sqf#L317-L326

**Comment by Jermin** [comment]
Yup. That's the culprit.

**Comment by AgentRev** [comment]
Ok, it doesn't depend on T or R, so I guess `reveal` is too taxing, I'll just chuck it out the door.
