### ISSUE TITLE
[Off topic] Alternate Engine

### ISSUE THREAD

**Issue by MaxManticore** [A3Wasteland/ArmA3_Wasteland.Altis#525]
Hello,

I know how annoying it is to get weird bug reports, so feel free to close this; just wasn't sure how to contact you otherwise.

I was impressed with you work here, I know the immense amount of effort and dedication that goes into work like this, and so I'm reaching out as I think you might be interested in a creation platform called Core (https://www.coregames.com/) that I'm a part of. 

For a quick list of Core's highlights:

- A robust 3D terrain and modeling editor - with thousands of free art and audio assets
- One-click publishing and hosting on our servers, within seconds
- Powerful Lua scripting with an extensive API, and over 20 gameplay frameworks to get you up and running fast

Here's our fantasy tileset video (https://youtu.be/M0cTBKeygOo), but know that we have plenty of military and weapon-based content as well - hence why I reached out to you specifically.

I wanted to keep it light for now, but am more than happy to provide additional specifics and resources :)

All the best,
Max

**Comment by AgentRev** [comment]
Your platform looks interesting, however I have shifted my focus away from game modding and more into real-world engineering. Best of luck to you and your team!

**Comment by JoSchaap** [comment]
Hey Rev!

Thanks for all your hard work and efforts!
You've turned this simple mission  into an amazing framework for others to express their creativity in.

Goodluck with your future endeavors.
I also am not expecting to return to arma 3.

I will keep the sites and domains running for as long as the costs do t bother me.

Kindest regards!

Jo


Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by PhilCS** [comment]
That's great, thanks. I still go on the site every now and then to answer questions.

**Comment by AgentRev** [comment]
That's great, thanks. I still go on the site every now and then to answer questions that arise.

**Comment by hobart666** [comment]
Much <3 & respek for you guys and all others that are A3 geniuses, I myself have stepped away from most gaming in general except for random drunken RS grinds. Thank yous guys for all your time & dedication and for putting up with ppl like myself and others more toxic than I. Rev you gonna go work for Elon Down here in the crusty states or what man? Shoot for the moon man (mars & beyond). <3 <3 <3 Joshaaaap you don't even know how much I respek you too man we've barely ever said much to one another I think maybe one thread, but yea man just knowing your history with wasteland and seeing your name all over the place for years since A2 wasteland, you've had a great impact as well on my brain over the years and I thank you too sir!
 ~The great Hobart

 P.S. Heeeyyy Revv, About them thermals I found in that genius spot... :dancing_men: you gonna give those back to the kiddies?
