### ISSUE TITLE
Add a way to rearm vehicles

### ISSUE THREAD

**Issue by JoSchaap** [A3Wasteland/ArmA3_Wasteland.Altis#57]
since my nifty ammo trucks are no longer in the convoy and truck mission, we need to organize some other way for players to re-arm armed vehicles.

**Comment by DemonseedElite** [comment]
I'm going to bump this one since it's been open since 2013 or so, and it's v1.3b now.  I don't see why a resupply truck that can re-outfit owned vehicles would be too terribly hard.  I might take a crack at it myself.

Make it work like the "Tow" system.  Walk up to the resupply truck, select "Resupply a vehicle..."  get a prompt for "Now select the vehicle you'd like to resupply".  Walk over to the nearby vehicle and select "Resupply this vehicle".   Do useless time-kill animation.  Done.   

Script sets all ammo counts back to new-spawn defaults.  

Similar actions could be done with fuel trucks.

**Comment by AgentRev** [comment]
It's already in v1,3b, in fact it's one of the new features...

**Comment by DemonseedElite** [comment]
It is?  I haven't been able to figure it out.  Tried damn near everything at this point.  Refuel trucks seemed to work in the 1.2b version I got from Steam a week ago, but when I compiled the 1.3b PBO from github to replace it, it was gone.  

-----Original Message-----
